-   id: update-django-environ-sample
    name: Automatically update env.sample
    description: Automatically update env.sample
    entry: update_django_environ_sample
    language: python
    always_run: true
    pass_filenames: false
